### ISSUE TITLE
오타가있습니다

### ISSUE THREAD

**Issue by SongHayoung** [sorrowhill/17techs#1]
안녕하세요 책을 잘 읽고있는 학생입니다!
1장관련해서 오타가 있는거 같습니다.
1.3 EUC-KR 관련해서 1바이트를 더한다가 아니라 1비트를 더한다 라고 생각합니다 혹시 제가 잘못알고 있는 부분이 있을까요?

**Comment by ggkollective** [comment]
안녕하세요. 말씀 주신 내용(26쪽) 확인해본 결과 1바이트가 아닌 1비트를 더하는 게 맞습니다 (__). 
해당 내용은 출판사 쪽과 이야기해서 수정 진행하겠습니다. 알려주셔서 감사합니다.

코로나 조심하시구요.
감사합니다.
